<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Exceções</title>
        <meta charset="utf-8">
        <script>
            var video = Array()
            video[1] = Array()
            video[1]['nome'] = 'Dragon Ball Z'
            video[1]['categoria'] = 'Anime'
            function getVideo(video){
                try{
                    console.log(video[1]['nome'])
                }catch(erro){
                    tratarErro(erro)
                    console.log('Agora sim podemos tratar esse erro')
                    throw new Error('Ouve um erro, mas não se preocupe, estamos trabalhando nisso')
                }finally{//Aplicado para try e catch
                    console.log('Sempre passa por aqui')
                }
                console.log('A aplicação não morreu')
            }
            function tratarErro(erro){
                console.log(erro)
                console.log('Agora sim podemos tratar esse erro')
            }
            getVideo(video)
        </script>
        <!--[if lt IE 9]>
	        <script src="js/html5shiv.js"></script>
        <![endif]-->
    </head>
    <body> 
       
    </body>
</html>